language: node_js
node_js:
- '8'
cache: yarn
script:
- npm run ci
deploy:
  provider: npm
  skip_cleanup: true
  email: rplan-ci@actano.de
  on:
    tags: true
    repo: actano/rplan-measure-it
    node: '8'
  api_key:
    secure: EWzTT/ZM2Uz5gz+qatnq25IPZ1eYyDrZa4Nzv71erS0R6uC89xBm9BMsnU7dLZH11eTsRk528DSYxW/49uN4obBA1qTpp34bTipuvZpF1uSMxmUnY6y7uUZAfLCEpxYm1HOugZrmr57TIdsqcj16ek3zvWZ9h8WfdhWCWRwUqoMPEqpOdzt+SAotD7IW/evsxfQ1GJzn/vrBHA+2BKKh7eCvh+tdpvmCszZn7De9W/IX6p+01+lNbSnRkOU2r8kLOj8bbCYrov/dG6kR9RnlN9Whn9JxW615yoFleNU6NbG9w0EOsIsSiGNDKlQ/7fAgh77oZS666xmo0ysvhN/7L6wmA1OqbNAl0MBqrjIOXfF1NmE9OG1K+KoUmOHacDihxhxwqPWEcJdTObunhhGDgfeUs3m6PoI2K/UfgLoMKQCs/yqtClmM4RgoRGRj7jpLjA0Cx2Wk9rDM1SXwqNFyrVTvTGM8dJcnQ6nPr/vuwyMkp021wTAaNamAParlA7m3LLv9pmCMqOSnpW2sTtoIhDUAiZwXUuXRiJr54OJOCFXINT6NyZzjKLSCx/B8G/0aYUSPnJrdntST/J8DQGMhk1erq0qN9JkilFryzSwr7qt9eXQpp3vVO1l6uOJOkgCMHsmkfU2t6A9mtItuGn9VvehjNCIplqlpTyh5qUScHCQ=
