name: Allex Measure It
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.puml'
      - '.gitignore'
    branches:
      - '*'
    tags:
      - '*'
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up NodeJS
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ matrix.node_version }}
      - name: Set Up NPM Authentication
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: CI=true npm clean-install
      - name: Lint
        run: CI=true npm run lint
      - name: Test
        run: CI=true npm run test
      - name: Build
        run: CI=true npm run build
      - name: NPM Publish
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        run: CI=true npm publish
